'use client';
import {useEffect,useState} from 'react';
import {createClient,listClients} from '@/lib/db';

type Client={id:string;name:string;company?:string;phone?:string;email?:string};
export default function Clientes(){const [clients,setClients]=useState<Client[]>([]);const [open,setOpen]=useState(false);const [name,setName]=useState('');const [company,setCompany]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [error,setError]=useState('');
async function load(){try{const r=await listClients();if(r.error)throw r.error;setClients((r.data||[]) as Client[])}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar clientes')}}useEffect(()=>{load()},[]);
async function save(e:React.FormEvent){e.preventDefault();try{const r=await createClient({name,company,phone,email});if(r.error)throw r.error;setName('');setCompany('');setPhone('');setEmail('');setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:'Erro ao criar cliente')}}
return <main style={{padding:32,fontFamily:'Arial',maxWidth:1200}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1>Clientes</h1><p>Clientes e histórico comercial.</p></div><button onClick={()=>setOpen(true)} style={{padding:'10px 15px'}}>+ Novo cliente</button></div>{error&&<p style={{color:'crimson'}}>{error}</p>}{open&&<form onSubmit={save} style={{padding:20,border:'1px solid #ddd',borderRadius:12,margin:'20px 0',display:'grid',gap:10,maxWidth:550}}><h2>Novo cliente</h2>{[['Nome',name,setName],['Empresa',company,setCompany],['Telefone',phone,setPhone],['Email',email,setEmail]].map(([l,v,s])=><label key={String(l)}>{l}<input required={l==='Nome'} value={v as string} onChange={e=>(s as (x:string)=>void)(e.target.value)} style={{display:'block',width:'100%',padding:9}}/></label>)}<div><button type="submit">Guardar</button> <button type="button" onClick={()=>setOpen(false)}>Cancelar</button></div></form>}<div style={{marginTop:20}}>{clients.length===0?<p>Nenhum cliente registado.</p>:clients.map(c=><div key={c.id} style={{padding:16,borderBottom:'1px solid #ddd'}}><strong>{c.name}</strong>{c.company&&<span> · {c.company}</span>}<div>{c.phone||''} {c.email&&`· ${c.email}`}</div></div>)}</div></main>}
